-- Cria a tabela principal do CRM.

-- ROTA CRM - schema + dados iniciais (171 empresas já cadastradas)
create table if not exists clients (
  id bigint generated by default as identity primary key,
  empresa text, razao_social text, nome_fantasia text, cnpj text, ie text,
  segmento text, contato text, telefone text, whatsapp text, email text,
  endereco text, cep text, cidade text, estado text,
  site text, instagram text, linkedin text,
  status text, etapa text, vendedor text,
  transportadora_atual text, concorrentes text, tipo_operacao text, volume_mensal text,
  modal text, necessidade text, dores text, objecoes text, diferenciais text,
  valor_potencial numeric default 0, probabilidade int default 30,
  proxima_acao text,
  timeline jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);
